import {
  AudioLines,
  BookOpen,
  CalendarCheck,
  CircleHelp,
  ClipboardCheck,
  Compass,
  Files,
  Flag,
  Footprints,
  GraduationCap,
  Languages,
  Library,
  ListChecks,
  Map as MapIcon,
  Medal,
  MessageCircle,
  MessagesSquare,
  Mic,
  Mountain,
  PenLine,
  Plane,
  Puzzle,
  Repeat,
  Sunrise,
  Target,
  TreeDeciduous,
  TrendingUp,
  Trophy,
  UserRound,
  Zap,
  Award,
  type LucideIcon,
} from 'lucide-react'

// Icons a badge_definitions.icon may name. A new badge with a new icon adds it here; an
// unknown name falls back to Award.
export const BADGE_ICONS: Record<string, LucideIcon> = {
  AudioLines,
  Award,
  BookOpen,
  CalendarCheck,
  ClipboardCheck,
  Compass,
  Files,
  Flag,
  Footprints,
  GraduationCap,
  Languages,
  Library,
  ListChecks,
  Map: MapIcon,
  Medal,
  MessageCircle,
  MessagesSquare,
  Mic,
  Mountain,
  PenLine,
  Plane,
  Puzzle,
  Repeat,
  Sunrise,
  Target,
  TreeDeciduous,
  TrendingUp,
  Trophy,
  UserRound,
  Zap,
}

export function badgeIcon(name: string | null): LucideIcon {
  if (name === null) return CircleHelp
  return BADGE_ICONS[name] ?? Award
}
