// Writes api/_lib/generated/examScoringPapers.ts: every Exam Prep paper with only what
// src/lib/examScoring.ts needs to score it (task and item ids, answers, rules), so the
// server can re-score a handed-in section for XP (api/_lib/examXp.ts) without shipping the
// passages and transcripts. The api can't import the paper files themselves: they import
// each other by `.ts` path, which only Vite and Node's type stripping resolve.
//
// Run after adding or correcting a paper: npm run gen:exam-keys (check:exams fails while
// the generated file is out of date). The output is committed.
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { examPaperLoaders, examPapers } from '../src/data/exams/catalog.ts'
import type { ExamItem, ExamPaper, ExamTask } from '../src/data/exams/types.ts'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const outFile = join(root, 'api', '_lib', 'generated', 'examScoringPapers.ts')

/** An item with its display text removed; the scoring fields stay. */
function stripItem(item: ExamItem): Record<string, unknown> {
  const base = { id: item.id, type: item.type }
  switch (item.type) {
    case 'choice':
    case 'mcq':
      return { ...base, answer: item.answer, ...(item.alsoAccept ? { alsoAccept: item.alsoAccept } : {}) }
    case 'boolean':
      return { ...base, answer: item.answer }
    case 'short-text':
    case 'correction':
      return { ...base, answer: item.answer }
    case 'order':
      return { ...base, first: item.first, answer: item.answer }
    case 'multi-select':
      return { ...base, options: item.options.map((o) => ({ key: o.key, text: '' })), answer: item.answer, pick: item.pick }
    case 'production':
      return base
  }
}

function stripTask(task: ExamTask): Record<string, unknown> {
  return { id: task.id, label: task.label, ...(task.rules ? { rules: task.rules } : {}), items: task.items.map(stripItem) }
}

function stripPaper(paper: ExamPaper): Record<string, unknown> {
  return {
    id: paper.id,
    type: paper.type,
    language: paper.language,
    level: paper.level,
    sections: paper.sections.map((s) => ({ id: s.id, kind: s.kind, titleHu: '', tasks: s.tasks.map(stripTask) })),
  }
}

export async function buildExamKeys(): Promise<string> {
  const papers: Record<string, unknown> = {}
  for (const meta of [...examPapers].sort((a, b) => a.id.localeCompare(b.id))) {
    const paper = (await examPaperLoaders[meta.id]()).default
    papers[meta.id] = stripPaper(paper)
  }
  return [
    '// GENERATED by scripts/build-exam-keys.ts — do not edit. Regenerate: npm run gen:exam-keys',
    '// Exam Prep papers reduced to their scoring fields (display text stripped), for',
    '// api/_lib/examXp.ts. Typed as ExamPaper: src/lib/examScoring.ts reads only the fields kept.',
    "import type { ExamPaper } from '../../../src/data/exams/types.js'",
    '',
    `export const EXAM_SCORING_PAPERS = ${JSON.stringify(papers)} as unknown as Record<string, ExamPaper>`,
    '',
  ].join('\n')
}

// Write unless imported (check-exam-papers.ts compares instead).
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const next = await buildExamKeys()
  let current = ''
  try {
    current = readFileSync(outFile, 'utf8')
  } catch {
    // First run.
  }
  if (current.replace(/\r\n/g, '\n') === next) {
    console.log('Exam scoring keys are up to date.')
  } else {
    writeFileSync(outFile, next)
    console.log(`Wrote ${outFile}`)
  }
}

export { outFile as examKeysFile }
