// Answer-key fixtures for the érettségi papers, read off each sitting's javítási-értékelési
// útmutató separately from the paper files. If a paper disagrees, re-read the PDF rather than
// editing the fixture.
//
//   keys: '<letters>' for choice/mcq items, 'T'/'F' style labels for boolean items, starting at
//         item id `first`; `text`: item id → every variant the key accepts; `ticks`: the ticked
//         option keys of a single multi-select item (with the tick count and option count);
//         `multi`: item id → ticked option keys, for one multi-select item per table row;
//         `order`: the right order of the parts of an ordering task, example part first.
export type TaskKey = { first: number; keys: string } | { text: Record<string, string[]> } | { ticks: string; pick: number; options: number }
  | { multi: Record<string, string> }
  | { order: string }
export type PaperKey = Record<string, TaskKey>

export const examKeys: Record<string, PaperKey> = {
  'erettsegi-de-kozep-2021-majus': {
    'I-1': { first: 1, keys: 'A C B F I D E' },
    'I-2': { text: { '8': ['Lebensmittelkontrolle', 'Lebensmittel untersuchen', 'Lebensmittel kontrollieren', 'Getränke untersuchen'], '9': ['sechs', 'nur sechs Getränke'], '10': ['sechs Teelöffel', 'höchstens sechs Teelöffel'], '11': ['die Hersteller süßen ihre Produkte weniger', 'weniger süße Produkte'], '12': ['gesunde Lebensmittel', 'über gesunde Lebensmittel'] } },
    'I-3': { text: { '13': ['sie sind jederzeit füreinander da', 'sie fühlen sich füreinander verantwortlich', 'sie möchten alles miteinander teilen'], '14': ['auf einer Geburtstagsparty'], '15': ['seit Anfang des Schuljahres', 'seit sie in eine Klasse gehen'], '16': ['bummeln', 'Serien schauen', 'über Jungs reden'], '17': ['weil Hannah mehr Zeit mit Alina verbringen möchte', 'weil Alina wenig Zeit für Hannah hat'], '18': ['trifft sich mit anderen Leuten', 'ärgert sich', 'ist sauer'], '19': ['die Mädchen sprechen sich aus', 'sie sprechen miteinander'], '20': ['weil sie nicht mehr in dieselbe Klasse gehen', 'ihre Wege haben sich getrennt', 'sie haben nicht dasselbe Umfeld'] } },
    'I-4': { first: 21, keys: 'D A E F H G B' },
    'II-1': { first: 1, keys: 'B B B C C D B D' },
    'II-2': { text: { '9': ['für'], '10': ['am'], '11': ['bei'], '12': ['mit'], '13': ['auf', 'bei'], '14': ['auf', 'von'], '15': ['seit'] } },
    'II-3': { first: 16, keys: 'E G F H D A' },
    'III-1': { first: 1, keys: 'F R F F R R R F R' },
    'III-2': { first: 10, keys: 'C C B B C B' },
    'III-3': { text: { '16': ['eine Kaffeemaschine', 'eine moderne Kaffeemaschine'], '17': ['Tradition', 'traditionelle Gründe', 'medizinische Gründe', 'Gesundheit'], '18': ['Tradition', 'traditionelle Gründe', 'medizinische Gründe', 'Gesundheit'], '19': ['die Muskeln des Magens', 'den Magen', 'die Verdauung'], '20': ['Thermoskannen', 'passenden Thermoskannen'], '21': ['das ganze Jahr über', 'im Sommer'] } },
  },
  'erettsegi-de-kozep-2021-oktober': {
    'I-1': { first: 1, keys: 'R F R F F R' },
    'I-2': { text: { '7': ['Schneewittchen', 'Charlie Chaplin'], '8': ['2005'], '9': ['Zeit'], '10': ['Fernsehen'], '11': ['einmal'], '12': ['im Keller'], '13': ['bemalt'] } },
    'I-3': { first: 14, keys: 'E D C B A F' },
    'I-4': { order: 'C A D F E H G B' },
    'II-1': { first: 1, keys: 'B B A A D A C C' },
    'II-2': { first: 9, keys: 'E D G B F' },
    'II-3': { text: { '14': ['im'], '15': ['mit', 'in'], '16': ['bis'], '17': ['von'], '18': ['zwischen'], '19': ['zu'], '20': ['in'] } },
    'III-1': { text: { '1': ['seit vier Wochen'], '2': ['30 Wochenstunden', '30 Stunden pro Woche'], '3': ['270 Euro', 'etwa 270 Euro im Monat'], '4': ['eine Sprache', 'Deutsch'], '5': ['aus der Ukraine'], '6': ['den Dialekt', 'den bayrischen Dialekt', 'die Kindersprache'], '7': ['Er übersetzt'], '8': ['in Deutschland bleiben', 'hier bleiben'] } },
    'III-2': { text: { '9': ['USA'], '10': ['300', 'fast 300'], '11': ['System', 'spezielles System'], '12': ['aktuell', 'sehr aktuell'], '13': ['den Namen', 'den Vornamen'], '14': ['in Zeitungen', 'in Magazinen'] } },
    'III-3': { ticks: 'a b e f g i', pick: 6, options: 10 },
  },
  'erettsegi-de-kozep-2022-majus': {
    'I-1': { first: 1, keys: 'K E D F L C J A B' },
    'I-2': { first: 10, keys: 'R F R F F R F R' },
    'I-3': { first: 18, keys: 'E B K J A G D F' },
    'II-1': { text: { '1': ['dem'], '2': ['das'], '3': ['einen'], '4': ['einem'], '5': ['der'], '6': ['das'], '7': ['das'] } },
    'II-2': { first: 8, keys: 'A C D C A B A' },
    'II-3': { first: 15, keys: 'B E F D H G' },
    'III-1': { text: { '1': ['Shanghai', 'China'], '2': ['sein Leben', 'Zusammenleben mit seiner Frau', 'Essen'], '3': ['sein Leben', 'Zusammenleben mit seiner Frau', 'Essen'], '4': ['das deutsche Leben', 'die Denkweise der Deutschen', 'die deutsche Seele'], '5': ['400.000', 'rund 400.000'], '6': ['er kann über sich selbst lachen', 'seine Figur', 'weiße Haut'], '7': ['Videos machen', 'ein zweites Buch schreiben'], '8': ['Videos machen', 'ein zweites Buch schreiben'] } },
    'III-2': { multi: { '9': '1', '10': '2', '11': '3', '12': '4', '13': '4', '14': '5' } },
    'III-3': { first: 15, keys: 'F R F F R R' },
  },
  'erettsegi-de-kozep-2022-oktober': {
    'I-1': { first: 1, keys: 'E F G A H D' },
    'I-2': { first: 7, keys: 'B H G D F E' },
    'I-3': { text: { '13': ['in den westdeutschen Großstädten', 'Großstädte', 'klassischen Universitätsstädten', 'Universitätsstädte'], '14': ['die billigste Wohnform', 'billig', 'günstig', 'preisgünstig'], '15': ['Behinderte', 'Studierende mit Kindern'], '16': ['Behinderte', 'Studierende mit Kindern'], '17': ['die Nähe zur Universität', 'die sozialen Kontaktmöglichkeiten', 'Kontakte'], '18': ['zwei Drittel', 'fast zwei Drittel'], '19': ['in Gästehäusern', 'Gästehäuser'] } },
    'I-4': { first: 20, keys: 'R R F R F F' },
    'II-1': { first: 1, keys: 'A C B A D D A' },
    'II-2': { first: 8, keys: 'P H D O A G I L' },
    'II-3': { first: 16, keys: 'G D F E H B' },
    'III-1': { ticks: 'b c f g i k l', pick: 7, options: 12 },
    'III-2': { first: 8, keys: 'A C A C B C' },
    'III-3': { text: { '14': ['keine Originalaufnahme', 'Originalaufnahmen'], '15': ['eine kleine Stadt', 'in der Nähe von Berlin'], '16': ['ein Weihnachtskonzert', 'Konzert'], '17': ['Moderatoren', 'Radiomoderatoren', 'Musiker'], '18': ['aus der Zeitung', 'Zeitung'], '19': ['wichtig'], '20': ['schnell'], '21': ['Fernseher'] } },
  },
  'erettsegi-de-kozep-2023-majus': {
    'I-1': { first: 1, keys: 'F R R F F R' },
    'I-2': { text: { '7': ['das mediterrane Klima', 'die große Auswahl an Möglichkeiten', 'viele Möglichkeiten', 'Die Region bietet einmalige Erlebnisse'], '8': ['drei', 'drei Länder', 'Deutschland, Österreich und die Schweiz'], '9': ['Personalausweis', 'einen Reisepass'], '10': ['mit dem Auto', 'mit dem Schiff', 'mit der Bahn', 'mit dem Rad'], '11': ['in kleineren Geschäften', 'in Gaststätten', 'beim Ticketkauf'], '12': ['in der Schweiz'], '13': ['Die meisten Gastgeber können Englisch', 'Man kann sich auf Englisch verständigen'], '14': ['durch die Temperatur des Sees', 'durch den See'] } },
    'I-3': { first: 15, keys: 'B F D A G' },
    'I-4': { order: 'G B C A F E D' },
    'II-1': { first: 1, keys: 'K M F A H D N O' },
    'II-2': { text: { '9': ['hatte'], '10': ['verkaufte'], '11': ['entstanden'], '12': ['gibt', 'gab'], '13': ['geblieben'], '14': ['geworden'] } },
    'II-3': { first: 15, keys: 'F B H A E G D' },
    'III-1': { multi: { '1/2': '2 4', '3': '3', '4': '3', '5': '5', '6': '1', '7': '1' } },
    'III-2': { first: 8, keys: 'F R F R F R F R' },
    'III-3': { text: { '16': ['früh', 'besonders früh'], '17': ['Hilfsaktion', 'die größte Hilfsaktion'], '18': ['eine Million'], '19': ['den Flughäfen', 'Flughäfen'], '20': ['Italien', 'Frankreich', 'Spanien', 'Portugal'], '21': ['aus eigener Kraft', 'selbst'] } },
  },
  'erettsegi-de-kozep-2023-oktober': {
    'I-1': { first: 1, keys: 'B A C D H E F' },
    'I-2': { first: 8, keys: 'R R F F R F' },
    'I-3': { first: 14, keys: 'D A B F G E' },
    'I-4': { text: { '20': ['Benutzerführung', 'ob die Apps auf allen Geräten laufen'], '21': ['Benutzerführung', 'ob die Apps auf allen Geräten laufen'], '22': ['in den Büroräumen', 'zu Hause'], '23': ['dokumentieren', 'schriftlich dokumentieren'], '24': ['fit auf seinem Gerät', 'kreativ', 'hat viele Apps genutzt', 'möchte viele Apps ausprobieren'], '25': ['16', 'mindestens 16 Jahre'] } },
    'II-1': { first: 1, keys: 'C D A B D C D D' },
    'II-2': { text: { '9': ['Ein'], '10': ['der'], '11': ['des', 'eines'], '12': ['ein'], '13': ['einer'], '14': ['denen'] } },
    'II-3': { first: 15, keys: 'D B F E G H' },
    'III-1': { multi: { '6': '5', '2': '2', '5': '4', '1': '1', '3': '2', '4/7': '3 5' } },
    'III-2': { first: 8, keys: 'F R R F R F R' },
    'III-3': { text: { '15': ['Spiel', 'das Spielen', 'spielen'], '16': ['Spielzeug', 'Formen', 'Kugeln', 'Würfel'], '17': ['Mütter und Väter'], '18': ['1840'], '19': ['Arbeitern', 'Arbeiterinnen und Arbeitern', 'Fabrikarbeiter'], '20': ['den USA'] } },
  },
  'erettsegi-de-kozep-2024-majus': {
    'I-1': { first: 1, keys: 'R R R R F F R F' },
    'I-2': { first: 9, keys: 'I E D A K F C B' },
    'I-3': { first: 17, keys: '1 1 2 2 3 3 3 4 4' },
    'II-1': { first: 1, keys: 'A C D D B D B D' },
    'II-2': { first: 9, keys: 'O D E I F N K M' },
    'II-3': { first: 17, keys: 'E C I A B F D' },
    'III-1': { first: 1, keys: 'F R R R F F R' },
    'III-2': { text: { '8': ['Fußgänger', 'Radfahrer'], '9': ['Kameras', 'mehreren Kameras'], '10': ['unterscheiden', 'erkennen', 'sehen'], '11': ['40', 'bis zu 40'], '12': ['vor einer Schule'], '13': ['Schüler', 'Schülerinnen und Schüler'], '14': ['schaltet sie sofort auf Grün', 'schaltet sie auf Grün', 'zeigt sie sofort Grün', 'zeigt sie Grün'] } },
    'III-3': { text: { '15': ['vier oder fünf', 'den Trainern zu helfen'], '16': ['findet es gut', 'findet gut', 'findet es schön', 'freut sich'], '17': ['Familiensport'], '18': ['80.000', 'Holland'], '19': ['Erwachsene', 'die Bundesligateams', 'die Top-Mannschaften'], '20': ['Menschen', 'Orte'], '21': ['Damenteam'] } },
  },
  'erettsegi-de-kozep-2024-oktober': {
    'I-1': { first: 1, keys: 'B G A D F H' },
    'I-2': { first: 7, keys: 'F R R F F R R' },
    'I-3': { multi: { '14/16': '1 2', '15/17/18': '1 2 3', '19/20': '3 4', '21': '4' } },
    'I-4': { first: 22, keys: 'G A E B D' },
    'II-1': { first: 1, keys: 'C D D D D A D C' },
    'II-2': { first: 9, keys: 'C L A K E F H' },
    'II-3': { first: 16, keys: 'B C E A F I D' },
    'III-1': { text: { '1': ['über 2000 Jahre', '2000 Jahre'], '2': ['Puppenhäuser', 'japanische Figuren', 'Eisenbahnen', 'aus der griechisch-römischen Zeit'], '3': ['älteste Kindermuseum'], '4': ['menschliche Herz', 'Herz'], '5': ['in die Hand nehmen', 'fotografieren'], '6': ['einen Vulkanstein', 'Stein'], '7': ['die Sprache der Liebe'] } },
    'III-2': { multi: { '8/12': 'u d', '10': 'u', '11/13': 'u d', '9': 'u', '14': 'd', '15': 'd' } },
    'III-3': { first: 16, keys: 'F R F F R R R F' },
  },
  'erettsegi-de-kozep-2025-oktober': {
    'I-1': { first: 1, keys: 'B I D H E A F' },
    'I-2': { multi: { '14': '6', '11': '4', '15': '7', '17': '9', '12/16': '5 8', '8': '1', '10': '3', '9/13': '2 5' } },
    'I-3': { first: 18, keys: 'K D A C F B E H' },
    'II-1': { first: 1, keys: 'I F H D O C K L' },
    'II-2': { text: { '9': ['wird'], '10': ['gewusst'], '11': ['machen'], '12': ['trainiert'], '13': ['eintreten'], '14': ['hält'], '15': ['war'], '16': ['herumfahre'] } },
    'II-3': { first: 17, keys: 'E D C A B' },
    'III-1': { first: 1, keys: 'R F R F F R F' },
    'III-2': { first: 8, keys: 'A A C B A A C' },
    'III-3': { ticks: 'c d e f i k', pick: 6, options: 11 },
  },
  'erettsegi-de-kozep-2026-majus': {
    'I-1': { first: 1, keys: 'H G E B A D K J F' },
    'I-2': { first: 10, keys: 'F R F R R F R' },
    'I-3': { first: 17, keys: 'H C B F A D L J K' },
    'II-1': { first: 1, keys: 'C B C A D A B' },
    'II-2': { first: 8, keys: 'D B M K F G N' },
    'II-3': { first: 15, keys: 'D H E B F A' },
    'III-1': { text: { '1': ['Südamerika'], '2': ['September und Oktober'], '3': ['Farbe'], '4': ['wäscht'], '5': ['bitteren'], '6': ['Kalorien', 'Energie'], '7': ['Suppe', 'Kuchen'] } },
    'III-2': { ticks: 'b d e f j k', pick: 6, options: 12 },
    'III-3': { first: 14, keys: 'F R R R R F F' },
  },
  'erettsegi-en-kozep-2021-majus': {
    'I-1': { first: 1, keys: 'H A D F I E' },
    'I-2': { first: 7, keys: 'C B C A A B' },
    'I-3': { first: 13, keys: 'E G B K H A F' },
    'I-4': { first: 20, keys: 'E K B L I A H F' },
    'II-1': { text: { '1': ['thanks'], '2': ['lovers'], '3': ['carefully'], '4': ['based'], '5': ['designer'], '6': ['imagine', 'imagined'], '7': ['protected'], '8': ['exhibition', 'exhibit'] } },
    'II-2': { first: 9, keys: 'D B A C D B C D' },
    'II-3': { text: { '17': ['was'], '18': ['it'], '19': ['at'], '20': ['that', 'which'], '21': ['best'], '22': ['what', 'everything', 'anything'], '23': ['of', 'showing'], '24': ['for'], '25': ['never', 'hadn\'t', 'hardly', 'scarcely', 'barely'] } },
    'III-1': { first: 1, keys: 'B A AB A B AB AB B A' },
    'III-2': { first: 10, keys: 'B A B A C C A' },
    'III-3': { text: { '17': ['products millionaires'], '18': ['high standards'], '19': ['write report'], '20': ['electrical equipment'], '21': ['21 passport', 'twenty-one passport'], '22': ['flexible timetable'], '23': ['reliable hard-working'], '24': ['50 65,000', 'fifty sixty-five thousand'], '25': ['email address'] } },
  },
  'erettsegi-en-kozep-2021-oktober': {
    'I-1': { first: 1, keys: 'H D A I F E B' },
    'I-2': { first: 8, keys: 'E H K B F D G' },
    'I-3': { first: 15, keys: 'E I D A G H' },
    'I-4': { first: 21, keys: 'C B C B B A A' },
    'II-1': { first: 1, keys: 'F E B K L G A H' },
    'II-2': { text: { '9': ['Welsh'], '10': ['recorded'], '11': ['European'], '12': ['used'], '13': ['internationally'], '14': ['programmer', 'programer'], '15': ['existing', 'existent'], '16': ['another'], '17': ['looking'] } },
    'II-3': { text: { '18': ['which'], '19': ['it'], '20': ['keep'], '21': ['to'], '22': ['with'], '23': ['called', 'named'], '24': ['next', 'close', 'near'], '25': ['of', 'on'] } },
    'III-1': { first: 1, keys: 'B B A C A C A B' },
    'III-2': { text: { '9': ['had lost it', 'lost the ticket', 'had lost her ticket'], '10': ['seven years', '7 years'], '11': ['store', 'shop'], '12': ['one percent', '1 percent', '1%', '$180,000', '180,000 dollars'], '13': ['new roof', 'roof'], '14': ['in the mountains'], '15': ['help her out financially', 'support her', 'give her some money'], '16': ['different charities', 'charity'], '17': ['forty million', '40 million', '40,000,000', '40m'] } },
    'III-3': { first: 18, keys: 'A B A AB B AB A AB' },
  },
  'erettsegi-en-kozep-2022-majus': {
    'I-1': { first: 1, keys: 'B A C B A B C' },
    'I-2': { first: 8, keys: 'I A K F B G E' },
    'I-3': { first: 15, keys: 'H E A D F K G' },
    'I-4': { first: 22, keys: 'I D A H F B' },
    'II-1': { text: { '1': ['difficulty'], '2': ['better'], '3': ['achievements'], '4': ['records'], '5': ['professional'], '6': ['extraordinary', 'out-of-the-ordinary', 'inordinary', 'unordinary'], '7': ['impossible'], '8': ['famous', 'famed'] } },
    'II-2': { first: 9, keys: 'H M G E L I K D' },
    'II-3': { text: { '17': ['to'], '18': ['their'], '19': ['by'], '20': ['of'], '21': ['his'], '22': ['for'], '23': ['have'], '24': ['that', 'which'], '25': ['one'] } },
    'III-1': { text: { '1': ['white stomach'], '2': ['length / bus'], '3': ['powerful tails'], '4': ['sharp teeth'], '5': ['small whales'], '6': ['drop / blood'], '7': ['gives birth'], '8': ['food chain'] } },
    'III-2': { first: 9, keys: 'B B B B A C A B' },
    'III-3': { first: 17, keys: 'A A B B AB B AB B' },
  },
  'erettsegi-en-kozep-2022-oktober': {
    'I-1': { first: 1, keys: 'H E K I B A F' },
    'I-2': { first: 8, keys: 'H G B E D' },
    'I-3': { first: 13, keys: 'C C B A C A B' },
    'I-4': { first: 20, keys: 'A G B H K F D I M' },
    'II-1': { text: { '1': ['pollution'], '2': ['natural'], '3': ['fashionable', 'in-fashion'], '4': ['description'], '5': ['offer'], '6': ['suitable'], '7': ['creative'], '8': ['environmental'] } },
    'II-2': { first: 9, keys: 'B C C A A D B B' },
    'II-3': { text: { '17': ['for'], '18': ['there', 'here'], '19': ['others', 'some', 'many'], '20': ['that', 'which'], '21': ['out', 'around'], '22': ['to'], '23': ['to', 'over', 'but'], '24': ['all'], '25': ['in'] } },
    'III-1': { text: { '1': ['Queen', 'queen'], '2': ['chemistry'], '3': ['1924'], '4': ['brain'], '5': ['research'], '6': ['heat'], '7': ['sailors'], '8': ['salt'], '9': ['retired'] } },
    'III-2': { first: 10, keys: 'B B C B A B C C B' },
    'III-3': { first: 19, keys: 'B B A C A A C' },
  },
  'erettsegi-en-kozep-2023-majus': {
    'I-1': { first: 1, keys: 'G F H B K L M I D' },
    'I-2': { first: 10, keys: 'H G D A I B' },
    'I-3': { first: 16, keys: 'B F D I E H' },
    'I-4': { first: 22, keys: 'B C B A A B C' },
    'II-1': { text: { '1': ['stressful', 'stressed', 'stressing'], '2': ['delayed'], '3': ['flying', 'flight'], '4': ['emergency', 'emergent', 'emerging'], '5': ['simpler'], '6': ['enjoyable'], '7': ['annoying'], '8': ['permission'], '9': ['immediately'] } },
    'II-2': { first: 10, keys: 'D H F K M A G I' },
    'II-3': { text: { '18': ['to'], '19': ['up'], '20': ['as', 'in', 'become', 'becoming', 'inspire'], '21': ['to'], '22': ['be', 'feel'], '23': ['like', 'resembling'], '24': ['makes'], '25': ['out', 'in', 'their'] } },
    'III-1': { text: { '1': ['trick'], '2': ['ingredient'], '3': ['eyesight', 'eye sight'], '4': ['stomach'], '5': ['lemon'], '6': ['rare', 'expensive'], '7': ['2,500'], '8': ['chemist'], '9': ['factories'] } },
    'III-2': { first: 10, keys: 'B B C A B B A C B' },
    'III-3': { first: 19, keys: 'B C C B A C C' },
  },
  'erettsegi-en-kozep-2023-oktober': {
    'I-1': { first: 1, keys: 'A K D M E B G F H' },
    'I-2': { first: 10, keys: 'D I A E L K G B' },
    'I-3': { first: 18, keys: 'F D E B G' },
    'I-4': { first: 23, keys: 'B C A A A C B A' },
    'II-1': { first: 1, keys: 'B D K L M F I G' },
    'II-2': { text: { '9': ['journalist'], '10': ['knowledge'], '11': ['importance'], '12': ['neighborhood', 'neighborhoods', 'neighbourhood', 'neighbourhoods'], '13': ['nearly', 'near'], '14': ['fast'], '15': ['changed'], '16': ['planting'] } },
    'II-3': { text: { '17': ['into'], '18': ['a', 'the'], '19': ['to'], '20': ['or'], '21': ['one'], '22': ['it'], '23': ['like'], '24': ['where'], '25': ['such'] } },
    'III-1': { text: { '1': ['journey'], '2': ['humans', 'crew', 'captain'], '3': ['ocean'], '4': ['historical'], '5': ['aluminum', 'aluminium'], '6': ['batteries'], '7': ['system'], '8': ['cameras'], '9': ['bathrooms'] } },
    'III-2': { first: 10, keys: 'B A AB A A AB A AB A' },
    'III-3': { first: 19, keys: 'A C A A B C A' },
  },
  'erettsegi-en-kozep-2024-majus': {
    'I-1': { first: 1, keys: 'F M I H A B L E' },
    'I-2': { first: 9, keys: 'B I G A K H D E' },
    'I-3': { first: 17, keys: 'H B I F D' },
    'I-4': { first: 22, keys: 'E I B D H A' },
    'II-1': { first: 1, keys: 'B I H E L D K G' },
    'II-2': { text: { '9': ['do'], '10': ['by'], '11': ['the', 'their', 'its'], '12': ['at', 'after', 'above'], '13': ['who', 'that', 'to'], '14': ['are', 'get'], '15': ['in'], '16': ['make', 'be'] } },
    'II-3': { text: { '17': ['recently'], '18': ['nearby'], '19': ['beautifully'], '20': ['hidden'], '21': ['owner'], '22': ['including'], '23': ['paintings'], '24': ['valuable', 'valued', 'invaluable'], '25': ['marriage'] } },
    'III-1': { first: 1, keys: 'A AB A B A B AB' },
    'III-2': { text: { '8': ['research'], '9': ['author'], '10': ['Sociology', 'sociology'], '11': ['culture'], '12': ['tool'], '13': ['human'], '14': ['chance'], '15': ['recovered', 'healed'], '16': ['serve', 'help'] } },
    'III-3': { first: 17, keys: 'C B A A C B A B A' },
  },
  'erettsegi-en-kozep-2024-oktober': {
    'I-1': { first: 1, keys: 'D G H A I F E' },
    'I-2': { first: 8, keys: 'D H G F B K I A' },
    'I-3': { first: 16, keys: 'B E F D H' },
    'I-4': { first: 21, keys: 'C A B B C A A C B' },
    'II-1': { first: 1, keys: 'I L H E M A B D F' },
    'II-2': { text: { '10': ['for', 'behind'], '11': ['as'], '12': ['the'], '13': ['well'], '14': ['to'], '15': ['it'], '16': ['keep'], '17': ['took'], '18': ['one'] } },
    'II-3': { text: { '19': ['Egyptians'], '20': ['length'], '21': ['including'], '22': ['use'], '23': ['reliable'], '24': ['following'], '25': ['development', 'developing'] } },
    'III-1': { text: { '1': ['traveller', 'traveler', 'originally'], '2': ['various'], '3': ['finger'], '4': ['shop'], '5': ['floor'], '6': ['trumpet'], '7': ['exhibitions'], '8': ['children'] } },
    'III-2': { first: 9, keys: 'A AB A B AB B B AB' },
    'III-3': { first: 17, keys: 'C A A C B B A B A' },
  },
  'erettsegi-en-kozep-2025-majus': {
    'I-1': { first: 1, keys: 'F H D G M L B K' },
    'I-2': { first: 9, keys: 'L A I B K G H E' },
    'I-3': { first: 17, keys: 'K I B D E H F' },
    'I-4': { first: 24, keys: 'C B C A A C B' },
    'II-1': { text: { '1': ['throwing'], '2': ['injuries'], '3': ['warning'], '4': ['lovers'], '5': ['rewarded'], '6': ['farther', 'further'], '7': ['typical'], '8': ['beginning'], '9': ['frozen', 'freezing'] } },
    'II-2': { first: 10, keys: 'B A D C B C B' },
    'II-3': { text: { '17': ['on'], '18': ['or'], '19': ['like'], '20': ['during', 'for', 'over', 'through', 'throughout'], '21': ['with'], '22': ['few', 'dozen'], '23': ['it'], '24': ['must', 'should'], '25': ['long', 'soon'] } },
    'III-1': { text: { '1': ['greet'], '2': ['extremely'], '3': ['late'], '4': ['important'], '5': ['customer'], '6': ['work'], '7': ['harder'], '8': ['Forces', 'forces'], '9': ['general', 'General'] } },
    'III-2': { first: 10, keys: 'A B AB B AB B B A' },
    'III-3': { first: 18, keys: 'B A B C A B B A' },
  },
  'erettsegi-en-kozep-2025-oktober': {
    'I-1': { first: 1, keys: 'K G A E I B' },
    'I-2': { first: 7, keys: 'G E M D A H I K B' },
    'I-3': { first: 16, keys: 'F E A H B' },
    'I-4': { first: 21, keys: 'B E A I H K' },
    'II-1': { text: { '1': ['extraordinary', 'unordinary'], '2': ['visited'], '3': ['fifth', '5th'], '4': ['fishing'], '5': ['heated'], '6': ['deaths'], '7': ['careful'], '8': ['reliable'] } },
    'II-2': { first: 9, keys: 'A C D A C A B D' },
    'II-3': { text: { '17': ['and', 'while', 'besides', 'or', 'thus', 'hence'], '18': ['it'], '19': ['of', 'showing', 'depicting', 'featuring'], '20': ['its'], '21': ['were'], '22': ['that', 'which'], '23': ['to'], '24': ['has'], '25': ['than'] } },
    'III-1': { text: { '1': ['unhappy'], '2': ['still'], '3': ['comfortable'], '4': ['teeth'], '5': ['serious'], '6': ['madness'], '7': ['tradition'], '8': ['afford', 'buy'], '9': ['acceptable'] } },
    'III-2': { first: 10, keys: 'A C B A B C A B' },
    'III-3': { first: 18, keys: 'B A A B A AB B AB' },
  },
  'erettsegi-en-kozep-2026-majus': {
    'I-1': { first: 1, keys: 'E G H L A M K D' },
    'I-2': { first: 9, keys: 'L G B I F K E' },
    'I-3': { first: 16, keys: 'C A B B A A C B A C' },
    'I-4': { first: 26, keys: 'H D G I A' },
    'II-1': { text: { '1': ['owner'], '2': ['lots'], '3': ['nervous', 'unnerved', 'nervy'], '4': ['arrival'], '5': ['sheep'], '6': ['breath'], '7': ['immediately'], '8': ['marvelous', 'marvellous'] } },
    'II-2': { first: 9, keys: 'C B C D D B C B' },
    'II-3': { text: { '17': ['it'], '18': ['to', 'and'], '19': ['for', 'on', 'during'], '20': ['to'], '21': ['like'], '22': ['a'], '23': ['their', 'the', 'both'], '24': ['why'], '25': ['as', 'like'] } },
    'III-1': { text: { '1': ['famous line'], '2': ['elderly couple'], '3': ['hungry for'], '4': ['chocolate sauce'], '5': ['on top'], '6': ['write down'], '7': ['in bed'], '8': ['ham sandwich'] } },
    'III-2': { first: 9, keys: 'B A C C B C B B' },
    'III-3': { first: 17, keys: 'B C A B B A B C B' },
  },
}
