import type { VercelRequest, VercelResponse } from '@vercel/node'
import { getUserFromRequest, supabaseAdmin } from './_lib/supabaseAdmin.js'
import { parseFeedbackJson } from './_lib/groq.js'
import { callModel } from './_lib/modelRouter.js'
import { logModelUsage } from './_lib/usageLog.js'
import { getModelForFeature } from './_lib/modelSettings.js'
import { getUserRole } from './_lib/roles.js'
import { getPersonaForRole, applyPersonaTokens } from './_lib/personas.js'
import { buildTutorSystemPrompt, buildTutorFeedbackPrompt } from './_lib/prompts.js'
import { getLearnerProfile, recordFeedbackToPersonalization } from './_lib/personalization.js'
import { addTutorWords } from './_lib/vocabTutorWords.js'
import { awardXp } from './_lib/gamification.js'
import { TUTOR_MIN_TURNS_FOR_XP } from '../src/lib/gamification/constants.js'
import type { AwardResult } from '../src/lib/gamification/types.js'
import type { ChatMessage, FeedbackResult } from '../src/lib/types.js'
import type { AddedTutorWord } from '../src/lib/vocab.js'
import { getSpeakingExam } from '../src/data/exams/speaking.js'
import type { SpeakingAssessRequest, SpeakingTurnRequest, SpeakingTurnResponse } from '../src/lib/examSpeakingTypes.js'
import {
  KICKOFF_MESSAGE as EXAM_KICKOFF_MESSAGE,
  buildAssessmentPrompt,
  buildExaminerSystemPrompt,
  learnerTurns,
  parseAssessment,
  parseExaminerReply,
  sanitizeHistory,
} from './_lib/examSpeaking.js'

// Single Vercel function for the whole /api/tutor surface (conversation turn,
// end-of-session feedback, and the nyelvvizsga speaking exam's examiner turns and
// assessment), multiplexed by ?action= to stay under Vercel Hobby's
// 12-serverless-function cap — do not add new files directly under api/.

const HISTORY_WINDOW = 4

// Soft anti-runaway guard, NOT a business rule — just a safety net so a stuck client
// can't loop forever calling Gemini. Change this freely; it isn't a session cap.
const MAX_TURN_INDEX = 40

const WRAP_UP_REPLY =
  "We've covered a lot today, so let's leave it there for now. Great job practicing — see you next time!"

const KICKOFF_MESSAGE: ChatMessage = {
  role: 'user',
  content: '(The learner has just opened the conversation. Greet them and start naturally, following the system prompt.)',
}

interface TutorChatRequestBody {
  history: ChatMessage[]
  turnIndex: number
  isFirstSession?: boolean
  personaId: string
  /** Generated by the browser when the conversation starts; absent from older clients. */
  sessionId?: string
}

const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

/**
 * Counts one learner turn in tutor_sessions (counts only, never message text) and awards
 * tutor-bot.conversation XP once, on the turn that reaches TUTOR_MIN_TURNS_FOR_XP. Never
 * throws: tracking must not stop the reply.
 */
async function trackTutorTurn(userId: string, sessionId: string, personaId: string): Promise<AwardResult | null> {
  try {
    const { data, error } = await supabaseAdmin.rpc('record_tutor_turn', {
      p_session_id: sessionId,
      p_user_id: userId,
      p_persona_id: personaId,
      p_min_turns: TUTOR_MIN_TURNS_FOR_XP,
    })
    if (error) throw error
    // No row: this session id belongs to another user, so it isn't tracked.
    const row = (data as Array<{ learner_turns: number; award_due: boolean }>)[0]
    if (!row?.award_due) return null
    return await awardXp({ userId, activityType: 'tutor-bot.conversation', itemRef: sessionId, language: 'en' })
  } catch (err) {
    console.error('Failed to track tutor session turn', err)
    return null
  }
}

async function buildSystemPrompt(
  userId: string,
  userEmail: string | undefined,
  isFirstSession: boolean,
  personaBlock: string,
): Promise<string> {
  const profile = await getLearnerProfile(userId, userEmail)

  const openingGuidance = isFirstSession
    ? "== OPENING THIS SESSION ==\nThis is the learner's first Tutor Bot session. Introduce yourself briefly and warmly, then ask what they'd like to work on or talk about today."
    : '== OPENING THIS SESSION ==\nThe learner has used Tutor Bot before. Give a short, personalized greeting — don\'t re-introduce yourself or re-ask what their goal is.'

  const resolvedPersonaBlock = applyPersonaTokens(personaBlock, { ...profile, openingGuidance })

  return buildTutorSystemPrompt({ ...profile, openingGuidance, personaBlock: resolvedPersonaBlock })
}

async function handleChat(req: VercelRequest, res: VercelResponse, userId: string, userEmail: string | undefined) {
  if (req.method !== 'POST') {
    res.status(405).json({ error: 'Method not allowed' })
    return
  }

  const body = req.body as TutorChatRequestBody

  const role = await getUserRole(userId)
  const persona = await getPersonaForRole(body.personaId, role)
  if (!persona) {
    res.status(400).json({ error: 'Unknown persona' })
    return
  }

  if (body.turnIndex >= MAX_TURN_INDEX) {
    res.status(200).json({ reply: WRAP_UP_REPLY, turnIndex: body.turnIndex, ended: true })
    return
  }

  const recentHistory = body.history.slice(-HISTORY_WINDOW)
  // Gemini's contents array can't be empty — the very first call of a session (no
  // history yet) needs a synthetic kickoff turn to prompt the opening line. Harmless
  // to include for Groq too, which has no such restriction.
  const historyForModel = recentHistory.length > 0 ? recentHistory : [KICKOFF_MESSAGE]
  const systemPrompt = await buildSystemPrompt(userId, userEmail, Boolean(body.isFirstSession), persona.promptText)
  const modelId = await getModelForFeature('tutorBot')

  let chatResult
  try {
    chatResult = await callModel(modelId, systemPrompt, historyForModel)
  } catch (err) {
    res.status(502).json({ error: err instanceof Error ? err.message : 'Model request failed' })
    return
  }

  await logModelUsage({
    userId,
    scenarioId: 'tutor-bot',
    callType: 'tutor_chat',
    modelId,
    usage: chatResult.usage,
  })

  // Only a request carrying a new learner message is a learner turn — the opening greeting
  // call has an empty history. Old clients send no sessionId and are simply not tracked.
  const isLearnerTurn = body.history.at(-1)?.role === 'user'
  const xp =
    isLearnerTurn && typeof body.sessionId === 'string' && UUID_PATTERN.test(body.sessionId)
      ? await trackTutorTurn(userId, body.sessionId, persona.id)
      : null

  res.status(200).json({ reply: chatResult.content, turnIndex: body.turnIndex, ended: false, xp })
}

interface TutorEndRequestBody {
  fullTranscript: ChatMessage[]
}

async function handleEnd(req: VercelRequest, res: VercelResponse, userId: string, userEmail: string | undefined) {
  if (req.method !== 'POST') {
    res.status(405).json({ error: 'Method not allowed' })
    return
  }

  const body = req.body as TutorEndRequestBody
  const modelId = await getModelForFeature('tutorBot')
  const fullTranscript = Array.isArray(body.fullTranscript) ? body.fullTranscript : []

  let feedback: FeedbackResult
  try {
    const { systemPrompt, messages } = buildTutorFeedbackPrompt(fullTranscript)
    const feedbackResult = await callModel(modelId, systemPrompt, messages)
    feedback = parseFeedbackJson(feedbackResult.content)

    await logModelUsage({
      userId,
      scenarioId: 'tutor-bot',
      callType: 'feedback',
      modelId,
      usage: feedbackResult.usage,
    })
  } catch {
    feedback = { strengths: [], corrections: [] }
  }

  let sessionId: string | null = null
  try {
    const { data, error } = await supabaseAdmin
      .from('sessions')
      .insert({
        user_id: userId,
        scenario_id: null,
        mode: 'tutor',
        transcript: fullTranscript,
        feedback,
      })
      .select('id')
      .single()
    if (error) throw error
    sessionId = data.id
  } catch (err) {
    console.error('Failed to save tutor session', err)
  }

  // Study targets go straight into the Vocabulary deck (design §5.2). Never fatal: the
  // learner still gets their feedback if this fails.
  let addedWords: AddedTutorWord[] = []
  try {
    const { cefrLevel } = await getLearnerProfile(userId, userEmail)
    addedWords = await addTutorWords(userId, feedback.vocabulary ?? [], cefrLevel)
  } catch (err) {
    console.error('Failed to add tutor words to the vocabulary deck', err)
  }

  await recordFeedbackToPersonalization(userId, feedback, modelId, { id: sessionId, source: 'tutor' })

  res.status(200).json({ feedback, addedWords })
}

/**
 * Speaking exam: one examiner turn of one task. The task text comes from the server's copy
 * (src/data/exams/speaking.ts); the browser sends only ids and this task's conversation.
 */
async function handleExamTurn(req: VercelRequest, res: VercelResponse, userId: string) {
  if (req.method !== 'POST') {
    res.status(405).json({ error: 'Method not allowed' })
    return
  }
  const body = (req.body ?? {}) as Partial<SpeakingTurnRequest>
  const exam = typeof body.paperId === 'string' ? getSpeakingExam(body.paperId) : undefined
  const task = exam?.tasks.find((t) => t.id === body.taskId)
  if (!exam || !task) {
    res.status(404).json({ error: 'Not found' })
    return
  }

  const history = sanitizeHistory(body.history)
  const turns = learnerTurns(history)
  // A turn arriving after the limit (or a stuck client) gets the examiner's closing line.
  const closeNow = turns >= task.maxLearnerTurns
  const systemPrompt = buildExaminerSystemPrompt({ exam, task, isOpening: history.length === 0, closeNow })
  const modelId = await getModelForFeature('tutorBot')

  let result
  try {
    result = await callModel(modelId, systemPrompt, history.length > 0 ? history : [EXAM_KICKOFF_MESSAGE])
  } catch (err) {
    res.status(502).json({ error: err instanceof Error ? err.message : 'Model request failed' })
    return
  }
  await logModelUsage({ userId, scenarioId: 'exam-speaking', callType: 'tutor_chat', modelId, usage: result.usage })

  const parsed = parseExaminerReply(result.content)
  const response: SpeakingTurnResponse = {
    reply: parsed.reply || "Thank you, that's the end of this task.",
    taskDone: parsed.taskDone || closeNow,
  }
  res.status(200).json(response)
}

/** Speaking exam: the AI's estimated scores and feedback for the whole exam. Nothing is stored. */
async function handleExamAssess(req: VercelRequest, res: VercelResponse, userId: string) {
  if (req.method !== 'POST') {
    res.status(405).json({ error: 'Method not allowed' })
    return
  }
  const body = (req.body ?? {}) as Partial<SpeakingAssessRequest>
  const exam = typeof body.paperId === 'string' ? getSpeakingExam(body.paperId) : undefined
  if (!exam) {
    res.status(404).json({ error: 'Not found' })
    return
  }
  const rawTranscripts = body.transcripts && typeof body.transcripts === 'object' ? body.transcripts : {}
  const transcripts = Object.fromEntries(exam.tasks.map((t) => [t.id, sanitizeHistory(rawTranscripts[t.id])]))
  if (exam.tasks.every((t) => learnerTurns(transcripts[t.id]) === 0)) {
    res.status(400).json({ error: 'Nothing to assess' })
    return
  }
  const uiLang = body.uiLang === 'en' || body.uiLang === 'de' ? body.uiLang : 'hu'
  const modelId = await getModelForFeature('tutorBot')

  try {
    const { systemPrompt, messages } = buildAssessmentPrompt({ exam, transcripts, uiLang })
    const result = await callModel(modelId, systemPrompt, messages)
    await logModelUsage({ userId, scenarioId: 'exam-speaking', callType: 'feedback', modelId, usage: result.usage })
    res.status(200).json(parseAssessment(result.content, exam, transcripts))
  } catch (err) {
    console.error('Speaking exam assessment failed', err)
    res.status(502).json({ error: 'Assessment failed' })
  }
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  const user = await getUserFromRequest(req)
  if (!user) {
    res.status(401).json({ error: 'Unauthorized' })
    return
  }

  const action = req.query.action

  switch (action) {
    case 'chat':
      await handleChat(req, res, user.id, user.email)
      return
    case 'end':
      await handleEnd(req, res, user.id, user.email)
      return
    case 'exam-turn':
      await handleExamTurn(req, res, user.id)
      return
    case 'exam-assess':
      await handleExamAssess(req, res, user.id)
      return
    default:
      res.status(404).json({ error: 'Not found' })
  }
}
